language: node_js
node_js:
  - node
env:
  global:
    - CC_TEST_REPORTER_ID: 398e5612cf31266c2a74f3c9c12aba91510b26bb410eee3f49cc5f44db2a05d6
install:
  - npm i
  - npm run install-sub-deps
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm run test
  - npm run build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT